package com.flightloglib.hibernate;
// Generated Aug 19, 2012 9:23:15 PM by Hibernate Tools 3.2.1.GA



/**
 * CrewMember generated by hbm2java
 */
public class CrewMember  implements java.io.Serializable {


     private long id;
     private long version;
     private Pilot pilot;
     private CrewMemberRole crewMemberRole;

    public CrewMember() {
    }

	
    public CrewMember(long id) {
        this.id = id;
    }
    public CrewMember(long id, Pilot pilot, CrewMemberRole crewMemberRole) {
       this.id = id;
       this.pilot = pilot;
       this.crewMemberRole = crewMemberRole;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }
    public Pilot getPilot() {
        return this.pilot;
    }
    
    public void setPilot(Pilot pilot) {
        this.pilot = pilot;
    }
    public CrewMemberRole getCrewMemberRole() {
        return this.crewMemberRole;
    }
    
    public void setCrewMemberRole(CrewMemberRole crewMemberRole) {
        this.crewMemberRole = crewMemberRole;
    }




}


