package com.flightloglib.hibernate;
// Generated Aug 19, 2012 9:23:15 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Pilot generated by hbm2java
 */
public class Pilot  implements java.io.Serializable {


     private long id;
     private long version;
     private String address1;
     private String address2;
     private String certificateNo;
     private String city;
     private String email;
     private String firstName;
     private String lastName;
     private String notes;
     private String phone;
     private String stateProvince;
     private String zip;
     private Set crewMembers = new HashSet(0);

    public Pilot() {
    }

	
    public Pilot(long id) {
        this.id = id;
    }
    public Pilot(long id, String address1, String address2, String certificateNo, String city, String email, String firstName, String lastName, String notes, String phone, String stateProvince, String zip, Set crewMembers) {
       this.id = id;
       this.address1 = address1;
       this.address2 = address2;
       this.certificateNo = certificateNo;
       this.city = city;
       this.email = email;
       this.firstName = firstName;
       this.lastName = lastName;
       this.notes = notes;
       this.phone = phone;
       this.stateProvince = stateProvince;
       this.zip = zip;
       this.crewMembers = crewMembers;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getCertificateNo() {
        return this.certificateNo;
    }
    
    public void setCertificateNo(String certificateNo) {
        this.certificateNo = certificateNo;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getStateProvince() {
        return this.stateProvince;
    }
    
    public void setStateProvince(String stateProvince) {
        this.stateProvince = stateProvince;
    }
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }
    public Set getCrewMembers() {
        return this.crewMembers;
    }
    
    public void setCrewMembers(Set crewMembers) {
        this.crewMembers = crewMembers;
    }




}


